---
execute:
  eval: true
  echo: true
  output: true
engine: knitr
format:
  html:
    toc: false
    number-sections: false
    colorlinks: true
    theme: default
title: scom-org colab
---

## 230329: sentiment analysis

```{r, purl=T}
#| eval: true
#| output: true
if (T) {
#load packages
library("tidyverse")
library("quarto")
#clear workspace
rm(list=ls())
}
```

```{r, purl=T}
#| eval: true
#| output: true
# working directory
if (!grepl("/qmd", getwd(), fixed=T)) {setwd("qmd/")}; getwd();
# load functions
vals_normalize <- function(x,y) {return (data.frame(id=x, nv=(y - min(y)) / (max(y) - min(y))))}
# load fb post dataset
fn = "https://raw.githubusercontent.com/nils-holmberg/scom-org/main/csv/fb-sa-230314.csv"
fn = "../csv/fb-sa-230314.csv"
dtp = read.table(fn, sep='\t', header=T, strip.white=TRUE, stringsAsFactors=FALSE)
```

## 230322: growth analysis

```{r, purl=T}
#| eval: true
#| output: true
#engagement over time
tmp = dtp %>% select(c(1,27,22,11)) %>% head()
#facet plot bivariate
#p = ggplot(tmp, aes(x=org_type, y=value)) +
#  geom_bar(position='dodge', stat='summary', fun='mean') +
#  facet_wrap(vars(measure), scales="free")
#p
```

```{r, purl=T}
#| eval: true
#| output: true
# dv1
tmp1 = dtp %>% select(c(3,22,11)) %>% 
group_by(org, month) %>% summarize(e_index_mean=mean(e_index))
# dv2
tmp2 = dtp %>% mutate(e_index_rel=e_index/follow) %>% select(c(3,22,28)) %>% 
group_by(org, month) %>% summarize(e_index_rel_mean=mean(e_index_rel))
# dv3
tmp3 = left_join(dtp %>% select(c(1,3,22,11)), dtp %>% select(c(1,3,22,11)) %>% 
group_by(org) %>% group_modify(~ vals_normalize(.x$id,.x$e_index)), by=c("org","id")) %>% 
select(c(2,3,5)) %>% rename(e_index_norm=nv) %>% 
group_by(org, month) %>% summarize(e_index_norm_mean=mean(e_index_norm))
# dv4
tmp4 = left_join(tmp1, tmp1 %>% 
group_by(org) %>% group_modify(~ vals_normalize(.x$month,.x$e_index_mean)) %>% rename(month=id, e_index_mean_norm=nv), by=c("org","month")) %>% select(-c(3))
# dvs, join multiple
tmp = tmp1 %>% 
left_join(tmp2, by=c("org","month")) %>% 
left_join(tmp3, by=c("org","month")) %>% 
left_join(tmp4, by=c("org","month"))
# dvs, wide to long
tmp = tmp %>% 
pivot_longer(cols=3:6, names_to="dvs", values_to="e_index")
# line plot
lp = ggplot(
data=tmp %>% filter(org %in% c("ClownerutanGranser","lakareutangranser")), 
aes(x=month, y=e_index, group=org, color=org)) +
  geom_line(size=1) +
  facet_wrap(vars(dvs), scales="free") +
  labs(title="engagement by org and measure")
lp
#  facet_wrap(~dvs)
#  facet_grid(. ~ dvs)
```

### long to wide format

```{r, purl=T}
#| eval: true
#| output: true
tmp1 = dtp %>% select(c(3,22,11)) %>% 
group_by(org, month) %>% summarize(e_index_mean=mean(e_index)) %>% 
pivot_wider(names_from=month, names_glue="month_{month}", values_from=e_index_mean)
```

### wide to long format

```{r, purl=T}
#| eval: true
#| output: true
tmp2 = tmp1 %>% 
pivot_longer(cols=2:61, names_to="month", values_to="e_index_mean")
# line plot
lp = ggplot(
data = tmp2 %>% filter(org %in% c("ClownerutanGranser","lakareutangranser")), 
aes(x=month, y=e_index_mean, group=org, color=org)) +
  geom_line()
lp
```

## 230315: bivariate org type

```{r, purl=T}
#wide to long format
tmp = dtp %>% select(c(1,27,6,11,14,24)) %>% pivot_longer(cols=3:6, names_to="measure", values_to="value")
#facet plot bivariate
p = ggplot(tmp, aes(x=org_type, y=value)) +
  geom_bar(position='dodge', stat='summary', fun='mean') +
  facet_wrap(vars(measure), scales="free")
p
```

## 230314: resume analysis 

```{r, purl=F}
if (T) {
knitr::knit_exit()
#exit()
#q()
#stop("here..")
}
```

```{r, purl=F}
#| eval: false
#| output: false
if (F) {
# dependencies
install.packages("tidyverse")
install.packages("lme4")
install.packages("plyr")
install.packages("quarto")
}
```

```{r, purl=F}
#| eval: false
#| output: false
#working directory
if (!grepl("/qmd", getwd(), fixed=T)) {setwd("qmd/")}
#clear workspace
rm(list=ls())
#run qmd notebook, dont do this.. 
#quarto::quarto_render("socm_sa.qmd")
#load functions
source("../src/emo-functions.R")
```

```{r, purl=F}
#| eval: false
fn = "https://raw.githubusercontent.com/nils-holmberg/scom-org/main/csv/fb-sa-230314.csv"
fn = "../csv/fb-sa-230314.csv"
dtp = read.table(fn, sep='\t', header=T, strip.white=TRUE, stringsAsFactors=FALSE)
#dtp[9,]
#str(dtp)
#knitr::knit_exit()
```

```{r, purl=F}
#| eval: false
ggplot(dtp, aes(org_type, e_index)) +
  geom_bar(position='dodge', stat='summary', fun='mean')
```

## 230305: resume analysis 

```{r, purl=F}
if (T) {
knitr::knit_exit()
}
```

### replicate project

some explanations of code cell in markdown..

```{r, purl=F}
#| eval: false
if (F) {
# clone github repo
usethis::create_from_github("https://github.com/nils-holmberg/scom-org.git", destdir = "/content/", fork = FALSE)
# go to repo dir
setwd("/content/scom-org/")
list.files()
# delete repo dir, to start over
unlink("/content/scom-org/", recursive=TRUE)
}
```

```{r, purl=F}
#| eval: false
if (F) {
# dependencies
install.packages("tidyverse")
install.packages("lme4")
install.packages("plyr")
}
```

### start here on posit.cloud

link here [posit](https://posit.cloud)

```{r, purl=F}
#| eval: false
if (F) {
# unzip data file
unzip("../csv/fb-sa-210305.csv.zip", exdir="../csv")
}
```

```{r, purl=F}
#| eval: false
#clear workspace
rm(list=ls())
#load functions
source("../src/emo-functions.R")
#
#get records, with emojis (191119)
dfp = posts_get(fn='../csv/fb-sa-210305.csv')
#
```

```{r, purl=F}
#| eval: false
#aggregate measures by organization
colv = c("e_index","sa_val","sa_int","sa_frq","wc","follow")
dfo = orgs_aggregate(dfp, colv)
#column indices
coli = data.frame(test=names(dfo),some=1:length(names(dfo))) %>% filter(!grepl("_se|frq|wc",test)) %>% pull(some)
knitr::kable(dfo %>% as_tibble() %>% select(all_of(coli)) %>% head(), format="pipe", digits=2, caption='aggregate', booktabs=TRUE)
```

### ingest new data

```{r, purl=F}
#| eval: false
#aggregate measures by organization, add org type variable
xls = readxl::read_excel("../tmp/fb-org-type-nw.xlsx", sheet=1)
xls = readxl::read_excel("../tmp/fb-org-type-nw-ng.xlsx", sheet=1)
xls = xls %>% slice(1:125) %>% select("org","Agreed type") #select("org","Typ")
xls = rename(xls, org_type="Agreed type")
dto = left_join(dfo, xls, by=join_by(org))
knitr::kable(dto, format="pipe", digits=2, caption='aggregate, org type', booktabs=TRUE)
```

```{r, purl=F}
#| eval: false
sum(table(dto$org_type))
```

### scale up

```{r, purl=F}
#| eval: false
dtp = left_join(dfp, xls, by=join_by(org)) %>% as_tibble()
table(dtp$org_type)
sum(table(dtp$org_type))
#str(dtp)
write.table(dtp, "../csv/fb-sa-230314.csv", sep="\t", quot=T, row.names=F)
```








